# Generated by Django 5.2.1 on 2025-05-11 23:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='career_highlights',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='career_goals',
            new_name='mission_statement',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='title',
            new_name='professional_title',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='personal_values',
            new_name='short_bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='professional_headshot',
        ),
        migrations.AddField(
            model_name='profile',
            name='core_skills',
            field=models.TextField(default=django.utils.timezone.now, help_text='Comma separated list of skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
